<?php
/**
 * @copyright Copyright (c) 2017 Kaicai Media LLC
 * @author luoweifeng <luoweifeng@kaicaimedia.com>
 */

namespace console\controllers;

use Yii;
use yii\base\Controller;

class BaseController extends Controller
{
    public $api_key = "";
    public $secret_key = "";
    public $symbol = "";
    public $contract_type = "";
    public $db_path = '';

    function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->api_key = Yii::$app->params['api_key'];
        $this->secret_key = Yii::$app->params['secret_key'];
        $this->symbol = Yii::$app->params['symbol'];
        $this->contract_type = Yii::$app->params['contract_type'];
        $dir_name = time().'-'.rand(100,999);
        $this->db_path = './leveldb_data/'.$dir_name;
    }
}