<?php
/**
 * @copyright Copyright (c) 2017 Kaicai Media LLC
 * @author luoweifeng <luoweifeng@kaicaimedia.com>
 */

namespace console\controllers;

use Yii;
use backend\controllers\src\ok\OKCoin;
use yii\base\Controller;

class SmltController extends Controller
{
    private $api_key = "";
    private $secret_key = "";
    private $symbol = "";
    private $contract_type = "";

    function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->api_key = Yii::$app->params['api_key'];
        $this->secret_key = Yii::$app->params['secret_key'];
        $this->symbol = Yii::$app->params['symbol'];
        $this->contract_type = Yii::$app->params['contract_type'];
    }

    public function actionIndex()
    {
        $dir_name = time().'-'.rand(100,999);
        $path = './leveldb_data/'.$dir_name;

        $db = new \LevelDB($path);
        $it = new \LevelDBIterator($db);
        while($it->valid()) {
            var_dump($it->key() . " => " . $it->current() . "\n");
        }
    }
}