<?php
/**
 * @copyright Copyright (c) 2017 Kaicai Media LLC
 * @author luoweifeng <luoweifeng@kaicaimedia.com>
 */

namespace console\controllers;

use Yii;
use backend\controllers\src\ok\OKCoin;

class StgController extends Controller
{
    private $api_key = "";
    private $secret_key = "";

    function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->api_key = Yii::$app->params['api_key'];
        $this->secret_key = Yii::$app->params['secret_key'];
    }

    public function actionIndex()
    {
        $client = new OKCoin(new \OKCoin_ApiKeyAuthentication($this->api_key, $this->secret_key));

        $params = array('symbol' => $this->symbol, 'contract_type' => $this->contract_type);


        $dir_name = time().'-'.rand(100,999);
        $path = './leveldb_data/'.$dir_name;
        if (!is_dir($path)){
            mkdir($path, 0777);
        }

        while (true){
            usleep(5000);
            $cur_trade_info = $client -> tickerApi($params);
            $db = new \LevelDB($path);
            $db->put(time(), json_encode($cur_trade_info));
        }
    }
}